### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Manawyrm** [jabdoa2/Asksin_OTA_Bootloader#8]
Hi,

your bootloader is currently missing any sort of license. 
This makes it impossible to integrate your bootloader into any binary distribution of firmware binaries (for example to flash onto AskSin boards) because the bootloader is licensed as "All rights reserved" at the moment. 

A license like MIT: https://choosealicense.com/licenses/mit/ would be ideal, because it allows the bootloader to be integrated in MIT and GPL licensed projects alike. 

Licenses like the Creative Commons (used by the AskSin++ project itself) are unfavorable for software projects, because they don't apply to and protect compiled binaries. 

Could you add an appropriate license agreement to your repo? (GitHub can help you, just add a new file called "LICENSE.md" via the web interface) 

Thanks,
Tobias

**Comment by jabdoa2** [comment]
Guess we can license this as MIT. Opinions?

**Comment by Manawyrm** [comment]
Sorry, not quite sure, who you're asking here. Have you sent the link to this issue to someone else? 

I'm in favor of the MIT license, and could open a pull request if it helps?

**Comment by TobleMiner** [comment]
MIT sounds fine to me. +1
